version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: funds_db
    volumes:
      - fund_search-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fund_search_net
    restart: unless-stopped


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - fund_search-es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - fund_search_net
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    networks:
      - fund_search_net
    depends_on:
      - elasticsearch
    restart: unless-stopped

  elastic-setup:
    image: curlimages/curl:8.2.1
    container_name: elastic-setup
    entrypoint: ["/bin/sh", "/usr/local/bin/setup-elastic.sh"]
    volumes:
      - ./setup-elastic.sh:/usr/local/bin/setup-elastic.sh:ro
    environment:
      ES_URL: "http://elasticsearch:9200"
      KIBANA_URL: "http://kibana:5601"
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - fund_search_net
    restart: "no"

volumes:
  fund_search-postgres-data:
  fund_search-es-data:

networks:
  fund_search_net:
    driver: bridge